# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Local Heroes

# This is the place to set up the contact form recipient
email: info@localheroesonline.com
description: >- # this means to ignore newlines until "baseurl:"
  Local Heroes is het e-commerce platform waarmee je eenvoudig en altijd
  via de app het aanbod van lokale ondernemers kan bestellen.
  Boodschappen doen via Local Heroes is een win-win-win.
  - Steun lokale ondernemers, versterk je buurt
  - Altijd verse en lekkere producten van de markt in huis
  - Bespaar tijd, geld én moeite
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.localheroesonline.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: localheroesNL
github_username:  localheroesonline
mixpanel-project-token: 624a5eaf9d84caf4c6c5af9a45a08a4a # production = d75409912bb950e41f6c85be92aba32d
mixpanel-api-host: https://api-eu.mixpanel.com
google_analytics: UA-260378921

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

incremental: true

paginate: 5
paginate_path: "/blog/page/:num"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
