# Short URL for Whatsapp Referral Code Campaign
[[redirects]]
from = "/warcc"
to = "https://www.localheroesonline.com/app.html#utm_source=email&utm_medium=whatsapp&utm_campaign=referral_code&utm_content=2021-06"
status = 301
force = true

# Short URL for Referral Code Campaign via the app itself
[[redirects]]
from = "/arcc"
to = "https://www.localheroesonline.com/app.html#utm_source=app&utm_medium=share&utm_campaign=referral_code&utm_content=2021-07"
status = 301
force = true

# https://jobs.localheroesonline.com redirects to https://localheroes.recruitee.com/
[[redirects]]
from = "https://jobs.localheroesonline.com/*"
to = "https://localheroes.recruitee.com/:splat"
status = 302
force = true

[[redirects]]
from = "https://giel.localheroesonline.com/*"
to = "https://goudsmit.tech/:splat"
status = 302
force = true

[[redirect]]
from = "https://www.localheroesonline.com/api/img/email/*"
to = "https://static.localheroesonline.com/email/:splat"
status = 302
force = true

[[redirect]]
from = "https://www.localheroesonline.com/api/img/*"
to = "https://static.localheroesonline.com/img/:splat"
status = 302
force = true

# https://www.localheroesonline.com/jobs redirects to https://localheroes.recruitee.com/
[[redirects]]
from = "/jobs"
to = "https://localheroes.recruitee.com/"
status = 200
force = true

# redirect meant to display a continuous google slideshow on the smart television of hub pickup #002 (back of the hub)
[[redirects]]
from = "/v2_a"
to = "https://docs.google.com/presentation/d/e/2PACX-1vTG-fP0i7zidUzli7DuFnM8hiaIjrqiZnGhTt4cOWLndjsJcjAwUtoe6Wu5dHUw6VfEDEZe9VR6bdo7/pub?start=true&loop=true&delayms=3000&slide=id.gb8b17a9f7c_0_1"
status = 302
force = true

# redirect meant to display a continuous google slideshow on the smart television of hub pickup #002 (front of the hub)
[[redirects]]
from = "/v2_v"
to = "https://docs.google.com/presentation/d/e/2PACX-1vT9YjiQtsXgkpFsGYIg5ASYIIURpSh4vVPKOzxKNpZG5UfHYMskxVc_o_PnO8WUNWwlHakkm1Y19r3X/pub?start=true&loop=true&delayms=3000"
status = 302
force = true

[[redirects]]
from = "/index.php"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/faq.php"
to = "/faq.html"
status = 200
force = true

[[redirects]]
from = "/disclaimer-web.php"
to = "/disclaimer-web.html"
status = 200
force = true

[[redirects]]
from = "/disclaimer-app.php"
to = "/disclaimer-app.html"
status = 200
force = true

[[redirects]]
from = "/privacyverklaring.php"
to = "/privacyverklaring.html"
status = 200
force = true

[[redirects]]
from = "/privacy.html"
to = "/privacyverklaring.html"
status = 200
force = true

[[redirects]]
from = "/privacy.php"
to = "/privacyverklaring.html"
status = 200
force = true

[[redirects]]
from = "/privacy"
to = "/privacyverklaring.html"
status = 200
force = true

[[redirects]]
from = "/terms-conditions.php"
to = "/terms-conditions.html"
status = 200
force = true

[[redirects]]
from = "/karv2.php"
to = "/karv2.html"
status = 200
force = true

[[redirects]]
from = "/*.php"
to = "/:splat"
status = 200
force = false